# Data Wrangling

## Introduction


## Data Landscape

The data provided (csv) has the following features:
+ timestamp (milliseconds with microsecond precision); 
+ channel 0 raw, 
+ channel 1 raw,
+ channel 0 high-passed, 
+ channel 1 high-passed (all in ADC counts); 
+ quaternion x, y, z, and w; 

The quaternion coordinates follow the convention:
The X-axis points West.
The Y-axis points South.
The Z-axis points Up.
+ gyroscope x, y, and z in degrees per second; 
+ accelerometer x, y, and z in meters per second squared; 

The accelerometer and gyroscope coordinates follow the ENU convention:
The X-axis points East.
The Y-axis points North.
The Z-axis points Up.
+ body movement label; 

The body movement coding is: 0 = standing #1, 1 = standing #2, 2 = walking, 3 = walking
fast, 4 = running.
+ repetition number (where there is one "repetition" for a given prompting window)

In [1]:
# Import necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Import raw data 

filepath = './raw/pison_data_interview.csv'
col_names = ['timestamp', 'channel_0', 'channel_1', 'channel_0_hp', 'channel_1_hp', 'q_x', 'q_y', 'q_z', 'q_w', 'g_x', 'g_y', 'g_z', 'a_x', 'a_y', 'a_z', 'body_movement', 'repetition']

df = pd.read_csv(filepath, names=col_names)

df.head()

,timestamp,channel_0,channel_1,channel_0_hp,channel_1_hp,q_x,q_y,q_z,q_w,g_x,g_y,g_z,a_x,a_y,a_z,body_movement,repetition
0,1514824.503,12535249,12566283,-11889,17295,0.32196,-0.596619,-0.621826,0.392090,-1.342870,1.063105,0.503576,-0.660156,-10.003906,1.21875,0,1
1,1514827.496,12536264,12559246,-2063,13384,0.32196,-0.596741,-0.621826,0.392029,-1.510729,1.175011,0.000000,-0.660156,-10.003906,1.21875,0,1
2,1514830.493,12538584,12565279,2757,16008,0.32196,-0.596741,-0.621765,0.391968,-1.230964,1.175011,-0.279765,-0.660156,-10.003906,1.21875,0,1
3,1514833.500,12546745,12567024,7504,5644,0.32196,-0.596741,-0.621765,0.391968,-1.230964,1.175011,-0.279765,-0.660156,-10.003906,1.21875,0,1
4,1514836.498,12537375,12545467,-3855,-15893,0.32196,-0.596802,-0.621765,0.391907,-1.063105,0.839294,-0.727388,-0.660156,-10.003906,1.21875,0,1

In [3]:
df.info

<bound method DataFrame.info of          timestamp  channel_0  channel_1  channel_0_hp  channel_1_hp  \
0      1514824.503   12535249   12566283        -11889         17295
1      1514827.496   12536264   12559246         -2063         13384
2      1514830.493   12538584   12565279          2757         16008
3      1514833.500   12546745   12567024          7504          5644
4      1514836.498   12537375   12545467         -3855        -15893
...            ...        ...        ...           ...           ...
14976  1618167.393   11942866   12916517        -32480        -78200
14977  1618170.388   11881160   12934589        -43544        -69885
14978  1618173.377   11869705   12927326        -25592        -73242
14979  1618176.442   11898127   12957446         40027        -17502
14980  1618179.410   11949480   12977401         79369          7782

            q_x       q_y       q_z       q_w         g_x          g_y  \
0      0.321960 -0.596619 -0.621826  0.392090   -1.342870     1.063105
1      0.321960 -0.596741 -0.621826  0.392029   -1.510729     1.175011
2      0.321960 -0.596741 -0.621765  0.391968   -1.230964     1.175011
3      0.321960 -0.596741 -0.621765  0.391968   -1.230964     1.175011
4      0.321960 -0.596802 -0.621765  0.391907   -1.063105     0.839294
...         ...       ...       ...       ...         ...          ...
14976 -0.312927 -0.112427 -0.932861  0.138855 -114.255844 -1219.997200
14977 -0.312927 -0.112427 -0.932861  0.138855 -114.255844 -1219.997200
14978 -0.264465 -0.108093 -0.946472  0.150146 -104.464080 -1181.054100
14979 -0.218140 -0.103271 -0.956909  0.161560  -94.336610 -1117.715300
14980 -0.218140 -0.103271 -0.956909  0.161560  -94.336610 -1117.715300

              g_z       a_x        a_y      a_z  body_movement  repetition
0        0.503576 -0.660156 -10.003906  1.21875              0           1
1        0.000000 -0.660156 -10.003906  1.21875              0           1
2       -0.279765 -0.660156 -10.003906  1.21875              0           1
3       -0.279765 -0.660156 -10.003906  1.21875              0           1
4       -0.727388 -0.660156 -10.003906  1.21875              0           1
...           ...       ...        ...      ...            ...         ...
14976   82.026960  0.363281  -1.464844 -9.00000              4           3
14977   82.026960  0.363281  -1.464844 -9.00000              4           3
14978  103.904560  0.363281  -1.464844 -9.00000              4           3
14979  125.782140  0.363281  -1.464844 -9.00000              4           3
14980  125.782140  0.363281  -1.464844 -9.00000              4           3

[14981 rows x 17 columns]>

In [4]:
df.dtypes

timestamp        float64
channel_0          int64
channel_1          int64
channel_0_hp       int64
channel_1_hp       int64
q_x              float64
q_y              float64
q_z              float64
q_w              float64
g_x              float64
g_y              float64
g_z              float64
a_x              float64
a_y              float64
a_z              float64
body_movement      int64
repetition         int64
dtype: object

In [5]:
df.describe()

,timestamp,channel_0,channel_1,channel_0_hp,channel_1_hp,q_x,q_y,q_z,q_w,g_x,g_y,g_z,a_x,a_y,a_z,body_movement,repetition
count,1.498100e+04,1.498100e+04,1.498100e+04,14981.000000,1.498100e+04,14981.000000,14981.000000,14981.000000,14981.000000,14981.000000,14981.000000,14981.000000,14981.000000,14981.000000,14981.000000,14981.000000,14981.000000
mean,1.566353e+06,1.253765e+07,1.251263e+07,62.550898,-2.571735e+02,0.263423,0.051271,0.111606,0.444427,6.407260,5.183960,2.237941,0.564972,-10.547218,2.064593,2.003071,1.991456
std,3.096750e+04,4.158465e+05,5.626673e+05,35397.290087,6.523863e+04,0.320534,0.395624,0.588643,0.335159,119.806613,346.986960,110.392775,7.242565,6.138921,6.852529,1.414352,0.815279
min,1.514825e+06,1.040201e+07,1.021268e+07,-422438.000000,-1.053204e+06,-0.897766,-0.777832,-1.000000,0.000000,-481.754550,-1830.891100,-623.763060,-34.382812,-48.960938,-27.765625,0.000000,1.000000
25%,1.538782e+06,1.245908e+07,1.233564e+07,-9221.000000,-1.041900e+04,0.032471,-0.085632,-0.304993,0.107849,-36.425343,-50.077854,-21.709728,-2.011719,-13.261719,-0.542969,1.000000,1.000000
50%,1.566517e+06,1.256078e+07,1.254805e+07,411.000000,3.980000e+02,0.230042,0.072815,0.036194,0.401611,-0.671435,-0.727388,1.678587,-0.363281,-9.816406,1.457031,2.000000,2.000000
75%,1.594422e+06,1.265877e+07,1.269320e+07,9792.000000,1.127500e+04,0.584961,0.329468,0.712097,0.754333,47.727833,50.413570,39.278942,3.582031,-7.398438,5.097656,3.000000,3.000000
max,1.618179e+06,1.419352e+07,1.504110e+07,640848.000000,1.726175e+06,0.905945,0.738708,1.000000,0.999268,427.312380,1828.317300,425.130220,37.671875,7.691406,33.898438,4.000000,3.000000

In [6]:
# check for rows with NaNs
df_NaNs = df[df.isna().any(axis=1)]
df_NaNs.head()

Empty DataFrame
Columns: [timestamp, channel_0, channel_1, channel_0_hp, channel_1_hp, q_x, q_y, q_z, q_w, g_x, g_y, g_z, a_x, a_y, a_z, body_movement, repetition]
Index: []

There are no rows with missing values.

In [7]:
# check for duplicated rows 
df_dups = df[df.duplicated()]
df_dups.head()

Empty DataFrame
Columns: [timestamp, channel_0, channel_1, channel_0_hp, channel_1_hp, q_x, q_y, q_z, q_w, g_x, g_y, g_z, a_x, a_y, a_z, body_movement, repetition]
Index: []

There are no duplicated rows.

## Save Copy to Interim

In [8]:
# save a copy to the interim folder for EDA use - do not modify the raw data!
# has been commented out to prevent saving multiple copies or rewriting saved copy

# clean_copy = df.to_csv('./interim/pison_data.csv')